//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zhoubin.Infrastructure.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zhoubin.Infrastructure.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 EAN_13编码要求，输入字符串必须13位以上。 的本地化字符串。
        /// </summary>
        public static string EAN13LengthMust13Bit {
            get {
                return ResourceManager.GetString("EAN13LengthMust13Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EAN_8编码要求，输入字符串必须8位以上。 的本地化字符串。
        /// </summary>
        public static string EAN8LengthMust8bit {
            get {
                return ResourceManager.GetString("EAN8LengthMust8bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高度必须大于0 的本地化字符串。
        /// </summary>
        public static string HeightMustGTZero {
            get {
                return ResourceManager.GetString("HeightMustGTZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的身份证号。 的本地化字符串。
        /// </summary>
        public static string IdCardTipMessage {
            get {
                return ResourceManager.GetString("IdCardTipMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放比例不能大于1和小于0 的本地化字符串。
        /// </summary>
        public static string ImageZoom {
            get {
                return ResourceManager.GetString("ImageZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 provider类型必须是CacheProvider类型的子类。 的本地化字符串。
        /// </summary>
        public static string InvalidProviderType {
            get {
                return ResourceManager.GetString("InvalidProviderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验类型 的本地化字符串。
        /// </summary>
        public static string NetCheckType {
            get {
                return ResourceManager.GetString("NetCheckType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入数据不正确。正确数据为整数长度不超过{0},小数长度不超过{1}. 的本地化字符串。
        /// </summary>
        public static string NumberCheckMessage {
            get {
                return ResourceManager.GetString("NumberCheckMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入数据不正确。正确数据为整数长度不超过{0}. 的本地化字符串。
        /// </summary>
        public static string NumberCheckMessageSecond {
            get {
                return ResourceManager.GetString("NumberCheckMessageSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的组织机构代码。 的本地化字符串。
        /// </summary>
        public static string OrganizationCodeTipMessage {
            get {
                return ResourceManager.GetString("OrganizationCodeTipMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽度必须大于0 的本地化字符串。
        /// </summary>
        public static string WidthMustGTZero {
            get {
                return ResourceManager.GetString("WidthMustGTZero", resourceCulture);
            }
        }
    }
}
